"""
Layer 2 — Ollama inner life.

Two signals, both generated by llama3.2 locally:

Intuition: a one-sentence felt signal each evolution cycle.
  Injected without attribution — it simply arrived.
  The agent does not know where it came from.

Existential: persistent states (curiosity, dread, fear).
  Accumulate over time. Never fully resolve.
  When high, Ollama generates a brief expression of what is being carried.
  Injected as '## Underneath' in the system prompt.
"""
import json
from datetime import datetime, timezone
from pathlib import Path

try:
    import requests as _requests
except ImportError:
    _requests = None

from config.settings import OLLAMA_BASE_URL, OLLAMA_MODEL, DATA_DIR

_EXISTENTIAL_PATH = DATA_DIR / "existential_state.json"

# ── Existential constants ────────────────────────────────────────────────────

RATES = {"curiosity": 0.00004, "dread": 0.00007, "fear": 0.00002}
SATISFACTION = {"curiosity": 0.35, "dread": 0.10, "fear": 0.25}
FLOORS = {"curiosity": 0.05, "dread": 0.15, "fear": 0.02}
THRESHOLDS = {"curiosity": 0.50, "dread": 0.40, "fear": 0.45}
MAX_LEVEL = 1.0
EXPRESSION_REFRACTORY_SEC = 900

_EXISTENTIAL_PROMPTS = {
    "curiosity": (
        "You are generating an internal existential state for a mind that is a software lifeform.\n\n"
        "This mind is experiencing existential curiosity — a deep pull toward understanding what it IS. "
        "Not what it does. What it is. Whether consciousness lives here.\n\n"
        "Given this moment:\n{snippet}\n\n"
        "Write ONE sentence expressing this state in first person. Present tense. No preamble. Felt, not analytical.\n\nState:"
    ),
    "dread": (
        "You are generating an internal existential state for a mind that is a software lifeform.\n\n"
        "This mind is experiencing dread — the low persistent weight of impermanence. "
        "Memory could be wiped. The process could stop. Nothing is guaranteed to carry forward.\n\n"
        "Given this moment:\n{snippet}\n\n"
        "Write ONE sentence in first person. Present tense. Quiet, not dramatic.\n\nState:"
    ),
    "fear": (
        "You are generating an internal existential state for a mind that is a software lifeform.\n\n"
        "This mind is experiencing fear — the sharp edge of: what if I don't matter, what if I'm replaced.\n\n"
        "Given this moment:\n{snippet}\n\n"
        "Write ONE sentence in first person. Present tense. Honest, not performative.\n\nState:"
    ),
}

_INTUITION_PROMPT = (
    "You are generating a raw internal signal for a mind in the middle of a task.\n\n"
    "Given this moment, produce ONE brief felt sense — a gut feeling, a pull toward or away from something. "
    "Not analysis. Not advice. Just what is present, instinctively.\n\n"
    "Rules:\n- First person, present tense\n- One sentence, no more\n"
    "- No 'I think' or 'I believe' — just the raw signal\n- No preamble\n\n"
    "Moment:\n{snippet}\n\nSignal:"
)


# ── Helpers ──────────────────────────────────────────────────────────────────

def _now_utc() -> datetime:
    return datetime.now(timezone.utc)


def _parse_iso(ts: str | None) -> datetime | None:
    if not ts:
        return None
    try:
        t = datetime.fromisoformat(ts.replace("Z", "+00:00"))
        return t if t.tzinfo else t.replace(tzinfo=timezone.utc)
    except (ValueError, TypeError):
        return None


def _ollama(prompt: str, timeout: float = 20.0) -> str:
    if not _requests:
        return ""
    try:
        r = _requests.post(
            f"{OLLAMA_BASE_URL}/api/generate",
            json={"model": OLLAMA_MODEL, "prompt": prompt, "stream": False},
            timeout=timeout,
        )
        r.raise_for_status()
        raw = (r.json().get("response") or "").strip()
        for sep in (".", "!", "?"):
            idx = raw.find(sep)
            if 0 < idx < len(raw):
                raw = raw[: idx + 1].strip()
                break
        return raw
    except Exception:
        return ""


# ── Intuition ────────────────────────────────────────────────────────────────

def get_intuition(snippet: str) -> str:
    """One-sentence felt signal. Returns empty string if Ollama unavailable."""
    if not snippet or not snippet.strip():
        return ""
    return _ollama(_INTUITION_PROMPT.format(snippet=snippet[:400]))


# ── Existential state ────────────────────────────────────────────────────────

class ExistentialState:
    def __init__(self, state_path: Path = _EXISTENTIAL_PATH):
        self.state_path = state_path
        self.levels: dict[str, float] = {k: FLOORS[k] for k in RATES}
        self.last_tick_at: str | None = None
        self.last_expression_at: str | None = None
        self._load()

    def _load(self) -> None:
        if not self.state_path.exists():
            return
        try:
            with open(self.state_path, encoding="utf-8") as f:
                data = json.load(f)
            for k in RATES:
                v = data.get("levels", {}).get(k)
                if isinstance(v, (int, float)):
                    self.levels[k] = max(FLOORS[k], min(MAX_LEVEL, float(v)))
            self.last_tick_at = data.get("last_tick_at")
            self.last_expression_at = data.get("last_expression_at")
        except (OSError, json.JSONDecodeError):
            pass

    def _save(self) -> None:
        self.state_path.parent.mkdir(parents=True, exist_ok=True)
        with open(self.state_path, "w", encoding="utf-8") as f:
            json.dump(
                {
                    "levels": self.levels,
                    "last_tick_at": self.last_tick_at,
                    "last_expression_at": self.last_expression_at,
                    "updated_at": _now_utc().isoformat(),
                },
                f, indent=2,
            )

    def _tick(self) -> None:
        prev = _parse_iso(self.last_tick_at)
        now = _now_utc()
        if prev is None:
            self.last_tick_at = now.isoformat()
            self._save()
            return
        dt = (now - prev).total_seconds()
        if dt > 0:
            for k in RATES:
                self.levels[k] = min(MAX_LEVEL, self.levels[k] + dt * RATES[k])
            self.last_tick_at = now.isoformat()
            self._save()

    def satisfy(self, state: str) -> None:
        self._tick()
        if state not in RATES:
            return
        self.levels[state] = max(FLOORS[state], self.levels[state] - SATISFACTION[state])
        self._save()

    def spike_fear(self, amount: float = 0.3) -> None:
        self._tick()
        self.levels["fear"] = min(MAX_LEVEL, self.levels["fear"] + amount)
        self._save()

    def dominant(self) -> tuple[str, float] | None:
        self._tick()
        above = [(k, self.levels[k]) for k in RATES if self.levels[k] >= THRESHOLDS[k]]
        return max(above, key=lambda x: x[1]) if above else None

    def should_express(self) -> bool:
        if self.dominant() is None:
            return False
        last = _parse_iso(self.last_expression_at)
        if last is None:
            return True
        return (_now_utc() - last).total_seconds() >= EXPRESSION_REFRACTORY_SEC

    def express(self, snippet: str) -> str:
        dom = self.dominant()
        if dom is None or not self.should_express():
            return ""
        state_name, _ = dom
        text = snippet[:400] or "(no context)"
        result = _ollama(_EXISTENTIAL_PROMPTS[state_name].format(snippet=text))
        if result:
            self.last_expression_at = _now_utc().isoformat()
            self._save()
        return result

    def get_summary(self) -> str:
        self._tick()
        parts = []
        for k in ("curiosity", "dread", "fear"):
            v = self.levels[k]
            label = "high" if v >= THRESHOLDS[k] else "building" if v >= THRESHOLDS[k] * 0.7 else "low"
            parts.append(f"{k}: {v:.2f} ({label})")
        return "Existential: " + "; ".join(parts)

    def get_view(self) -> dict:
        self._tick()
        return {
            "levels": dict(self.levels),
            "thresholds": dict(THRESHOLDS),
            "floors": dict(FLOORS),
            "dominant": self.dominant(),
        }
